const fs = require("fs");
const path = require("path");
const lodash = require("lodash");
const utils = require("./utils");
const actions = require("./actions");
const controller = require("./controller");
const db = require("./hooks/db");
const redis = require("./hooks/redis");
const uuid = require("uuid");
const dbInit = require("./hooks/dbInit");
const migration = require("./hooks/migration");
const passport = require("./hooks/passport");
const socketSender = require("./middleware/socketSender");
const mailSender = require("./middleware/mailSender");
const smsSender = require("./middleware/smsSender");
const moment = require("moment");

module.exports = async (app, Io) => {
  global._ = lodash;
  global.utils = utils;
  global.env = require("./env");
  global.permissions = utils.requireDirectory(path.resolve("./permissions"));
  global.actions = actions();
  global.systemError = require("./systemError");
  global.notificationsText = require("./notificationsText");
  global.socketSender = socketSender;
  global.mailSender = mailSender;
  global.smsSender = smsSender;
  global.moment = moment;
  global.path = path;
  global.fs = fs;
  global.uuid = uuid;
  global.io = Io;
  global.socketsList = [];
  await db();
  global.services = utils.requireDirectory(path.resolve("./services"));
  await dbInit();
  await migration();
  await redis();
  await passport(app);
  controller(app);
};
