module.exports = {
  appointments: {
    cannotFindAppointment: "CANNOT_FIND_APPOINTMENT",
    cannotInsertNewAppointment: "CANNOT_INSERT_NEW_APPOINTMENT",
    cannotUpdateAppointment: "CANNOT_UPDATE_APPOINTMENT",
    duplicateAppointment: "DUPLICATE_APPOINTMENT",
    notValidDate: "NOT_VALID_DATE",
    notValidDoB: "NOT_VALID_DoB",
  },
  users: {
    accountAlreadyActivated: "ACCOUNT_ALREADY_ACTIVATED",
    accountIsInActive: "ACCOUNT_IS_INACTIVE",
    accountTypeIsInvalid: "ACCOUNT_TYPE_IS_INVALID",
    accountWasSuspended: "ACCOUNT_WAS_SUSPENDED",
    accountWasTrashed: "ACCOUNT_WAS_TRASHED",
    cannotFindUser: "CANNOT_FIND_USER",
    cannotInsertNewUser: "CANNOT_INSERT_NEW_USER",
    cannotUpdateUser: "CANNOT_UPDATE_USER",
    duplicateUser: "DUPLICATE_USER",
    invalidVerificationCode: "INVALID_VERIFICATION_CODE",
    notValidEmaiAddress: "NOT_VALID_EMAIL_ADDRESS",
    notValidMobileNumber: "NOT_VALID_MOBILE_NUMBER",
    passwordNotStrong: "PASSWORD_NOT_STRONG",
    tryAgainInAFewMinutes: "TRY_AGAIN_IN_A_FEW_MINUTES",
  },
};
